export const MenuData = [
    {
        name:'首页',
        path:'/',
        key:'index',
        icon:'appstore'
    },
    {
        name:'数据管理',
        key:'data',
        icon:'file',
        children:[
            {
                name:'用户列表',
                path:'/data/userList',
                key:'userList'
            },
            {
                name:'商家列表',
                path:'/data/shopList',
                key:'shopList'
            },
            {
                name:'食品列表',
                path:'/data/foodList',
                key:'foodList'
            },
            {
                name:'订单列表',
                path:'/data/orderList',
                key:'orderList'
            },
            {
                name:'管理员列表',
                path:'/data/adminList',
                key:'adminList'
            }
        ]
    },
    {
        name:'添加数据',
        key:'addData',
        icon:'plus',
        children:[
            {
                name:'添加商铺',
                path:'/addData/addShop',
                key:'addShop'
            },
            {
                name:'添加食品',
                path:'/addData/addGoods',
                key:'addGoods'
            }
        ]
    },
    {
        name:'图表',
        key:'chart',
        icon:'dot-chart',
        children:[
            {
                name:'用户分布',
                path:'/chart/user',
                key:'user'
            }
        ]
    },
    {
        name:'编辑',
        key:'edit',
        icon:'edit',
        children:[
            {
                name:'文本编辑',
                path:'/edit/text',
                key:'text'
            }
        ]
    },
    {
        name:'设置',
        key:'settings',
        icon:'setting',
        children:[
            {
                name:'管理员设置',
                path:'/settings/adminSettings',
                key:'adminSettings'
            }
        ]
    },
    {
        name:'说明',
        key:'explains',
        icon:'info-circle-o',
        children:[
            {
                name:'说明',
                path:'/explain',
                key:'explain'
            }
        ]
    }
]
